import type { Service } from "./types";
import { close, engage, process, service, solve, talk } from "./links";

export const adoptionEnablement: Service = {
    slug: "adoption-enablement",
    number: "07",
    icon: "graduation",
    title: "Adoption & Enablement",
    cardDescription: "Technology only delivers when your people know how to use it.",
    eyebrow: "07 · Enablement",
    headline: "Technology only delivers when your people know how to use it.",
    highlight: "your people",
    summary:
        "Structured training and enablement for admins, agents, supervisors, and end users — at launch, during change, and as an ongoing capability that keeps your technology investment performing long after go-live.",
    heroImage: {
        src: "/services/adoption-enablement.jpg",
        alt: "A trainer working with employees during a platform enablement session",
    },
    accentColor: "#5A5372",
    bgTint: "#F2F1F6",
    primaryCta: { label: "Plan your enablement programme", href: close },
    secondaryCta: { label: "Download training methodology", href: close },
    problem: {
        eyebrow: "What we solve",
        title: "Technology delivers value only when people use it",
        intro: "From pre-go-live readiness to ongoing enablement, we help teams adopt, embrace, and maximize the value of every technology investment.",
        pains: [
            {
                title: "Low adoption after go-live",
                body: "Teams that weren't adequately prepared before go-live revert to familiar habits — using old tools, building workarounds, and avoiding new features. Structured pre-go-live enablement prevents this from the start.",
            },
            {
                title: "Training that doesn't match the deployed configuration",
                body: "Generic vendor training teaches the platform as designed — not as you've configured it. Our training is built around your specific setup, your workflows, and your team's actual day-to-day responsibilities.",
            },
            {
                title: "No ongoing capability after the launch training",
                body: "Most organizations invest in launch training and nothing else — leaving new starters undertrained and existing staff uninformed about new features. Ongoing enablement keeps capability current as platforms evolve.",
            },
        ],
    },
    offeringsIntro: {
        eyebrow: "Enablement capabilities",
        title: "Training built around your deployment",
        body: "Admins, agents, supervisors, and end users each get a programme matched to the configuration you actually run — at launch, during change, and as the platform keeps moving.",
    },
    offerings: [
        {
            id: "admin-training",
            number: "01",
            title: "Admin & Technical Training",
            lede: "Platform administration and troubleshooting training built around your specific configuration — not the vendor's generic guide.",
            body: "Your IT and operations team need to understand the platform they're administering at a level that lets them make configuration changes, troubleshoot incidents, and onboard new users without calling Sysgrate for every question. We deliver structured admin training built around your specific deployment.",
            includedLabel: "What's included",
            included: [
                "Platform administration training — user provisioning, policy management, configuration updates, and system monitoring",
                "Contact center admin — routing flow management, queue configuration, IVR updates, and reporting setup",
                "UC platform admin — Zoom Phone or Teams voice administration, dial plan management, and device provisioning",
                "Integration administration — CRM connector management, field mapping updates, and basic troubleshooting",
                "Troubleshooting methodology — systematic approach to identifying and resolving the most common platform issues",
                "Runbook development — customized admin runbooks built specifically for your deployed configuration",
            ],
            primaryCta: { label: "Plan admin training", href: close },
            secondaryCta: { label: "Talk to a specialist", href: close },
        },
        {
            id: "agent-training",
            number: "02",
            title: "Agent & Supervisor Training",
            lede: "Role-specific training that makes agents effective on day one and supervisors confident in managing performance from week one.",
            body: "Contact center agents and supervisors have different platform needs — and training that ignores that distinction fails both groups. Our agent training focuses on the workflows, tools, and AI features that directly affect handle time, CSAT, and first-contact resolution — while our supervisor training covers reporting, coaching tools, and performance dashboards.",
            includedLabel: "What's included",
            included: [
                "Agent workspace training — call handling, channel switching, disposition, and after-call workflow in your configured environment",
                "AI assist tools training — agent assist, real-time transcription, knowledge base search, and AI summary features",
                "CRM navigation and data entry — how to use screen pops, log interactions, and update records correctly from day one",
                "Supervisor dashboard training — queue monitoring, real-time agent performance, and live intervention tools",
                "Quality management training — call scoring, coaching conversation structure, and performance review processes",
                "Workforce management training — schedule adherence, shift bidding, and intraday management tools",
            ],
            primaryCta: { label: "Plan agent training", href: close },
            secondaryCta: { label: "See how we work", href: process },
        },
        {
            id: "end-user",
            number: "03",
            title: "End-User Enablement",
            lede: "Structured onboarding and ongoing enablement for employees using Zoom, Microsoft Teams, and collaboration tools.",
            body: "UCaaS and collaboration platform rollouts succeed or fail on end-user adoption. We structure end-user enablement programmes around learning stages, role-based needs, and ongoing reinforcement — so adoption grows over time rather than peaking at launch and declining.",
            includedLabel: "What's included",
            included: [
                "Role-based training paths — different enablement programmes for office workers, remote employees, and mobile-first users",
                "Live training sessions — in-person or virtual, structured around your rollout phasing and geographic distribution",
                "Self-paced e-learning modules — platform-specific content your team can complete at their own pace post-rollout",
                "Quick-reference guides — role-specific one-pagers for the most common tasks, printed and digital",
                "New starter onboarding — structured platform onboarding for employees joining after the initial rollout",
                "Feature adoption campaigns — targeted enablement for new platform features as they're released",
            ],
            primaryCta: { label: "Plan end-user enablement", href: close },
            secondaryCta: { label: "Explore Digital Workplace solutions", href: solve },
        },
        {
            id: "change-management",
            number: "04",
            title: "Change Management Support",
            lede: "The people side of technology transformation — communications, stakeholder management, and change readiness built into every deployment.",
            body: "Technology transformations that treat change management as an afterthought consistently underperform. Resistance to new platforms, confusion about why the change is happening, and a lack of leadership alignment are the most common reasons enterprise technology deployments fall short of their adoption targets.",
            includedLabel: "What's included",
            included: [
                "Change impact assessment — mapping which teams, roles, and processes are affected and to what degree",
                "Stakeholder mapping and engagement plan — identifying champions, resistors, and neutrals with engagement designed for each",
                "Communications strategy — planned campaign from announcement through to post-go-live reinforcement",
                "Leadership alignment sessions — equipping senior leaders to communicate the change clearly and consistently",
                "Change readiness assessment — measuring organizational readiness before go-live and addressing gaps",
                "Resistance management — a structured approach to identifying and resolving adoption blockers at the team and individual level",
            ],
            primaryCta: { label: "Build your change plan", href: close },
            secondaryCta: { label: "See how we work", href: process },
        },
        {
            id: "certification",
            number: "05",
            title: "Certification Preparation",
            lede: "Structured preparation for Zoom, AWS, Avaya, and Microsoft certifications — building in-house platform expertise your organization can depend on.",
            body: "Enterprises that invest in internal platform certifications reduce their dependency on external support, resolve issues faster, and extract more value from their technology investment. We deliver structured certification preparation for IT teams across Zoom, Amazon Connect, Avaya, Microsoft Teams, and Zendesk.",
            includedLabel: "What's included",
            included: [
                "Certification pathway planning — identifying which certifications add the most value for each team member's role",
                "Structured study programmes — learning paths aligned to specific certification exam requirements",
                "Hands-on lab environments — practice environments where candidates can build and configure without risk to production",
                "Exam preparation workshops — focused sessions on the topics most commonly tested in each exam",
                "Practice assessments — mock exam conditions with detailed feedback on knowledge gaps",
                "Post-certification CPD — continuing development plan to maintain certification currency as platforms evolve",
            ],
            primaryCta: { label: "Plan your certification programme", href: close },
            secondaryCta: { label: "Talk to a specialist", href: close },
        },
        {
            id: "custom-training",
            number: "06",
            title: "Custom Training Development",
            lede: "Bespoke training materials, e-learning modules, and quick-reference guides — built for your specific platform configuration.",
            body: "Generic vendor training covers the platform as designed — not as you've configured it. We develop custom training content built around your exact deployment, your team's actual tasks, and your organization's language and branding.",
            includedLabel: "What's included",
            included: [
                "E-learning module development — platform-specific interactive modules built for your LMS or delivered standalone",
                "Video walkthrough production — screen-recorded workflow demonstrations tailored to your configured environment",
                "Quick-reference cards — role-specific one-page guides for the most frequent tasks on each platform",
                "Facilitator guides — structured delivery guides for internal trainers running sessions independently",
                "Assessment development — knowledge checks and competency assessments aligned to your training objectives",
                "Content maintenance — training material updates delivered when your platform configuration changes significantly",
            ],
            primaryCta: { label: "Develop your training content", href: close },
            secondaryCta: { label: "Download training methodology", href: close },
        },
    ],
    process: {
        eyebrow: "How we deliver",
        title: "We measure adoption — not just training attendance",
        intro: "Enablement is sequenced around the rollout, then kept alive after go-live so capability doesn't peak on launch day and fade.",
        steps: [
            {
                number: "Pre go-live",
                title: "Prepare",
                body: "Training needs analysis, content development, and champion identification — all completed before go-live.",
            },
            {
                number: "Go-live",
                title: "Enable",
                body: "Structured training delivery — admin, agent, supervisor, and end-user sessions sequenced around your rollout phasing.",
            },
            {
                number: "Weeks 2–4",
                title: "Reinforce",
                body: "Floor walking support, drop-in Q&A, adoption monitoring, and targeted follow-up for low-adoption teams.",
            },
            {
                number: "Ongoing",
                title: "Sustain",
                body: "New starter onboarding, feature adoption campaigns, and annual refreshers as your technology evolves.",
            },
        ],
    },
    relatedIntro:
        "Adoption & Enablement typically runs alongside Solution Design & Delivery and is often embedded within Experience as a Service engagements for organizations that need continuous training, onboarding, and user adoption support.",
    related: [
        {
            title: "Solution Design & Delivery",
            blurb: "Adoption starts long before go-live. Our enablement programs are built alongside every deployment to ensure users are prepared, confident, and ready from day one.",
            href: service("solution-design-delivery"),
        },
        {
            title: "Experience as a Service",
            blurb: "Continuous platform improvement requires continuous learning. XaaS engagements include ongoing training, onboarding, and capability development to keep teams aligned as technology evolves.",
            href: service("experience-as-a-service"),
        },
        {
            title: "Embedded Expertise",
            blurb: "When organizations need deeper capability development, our embedded specialists provide hands-on coaching, knowledge transfer, and user enablement within day-to-day operations.",
            href: engage,
        },
    ],
    close: {
        title: "Ready to build an enablement programme that makes your technology investment perform?",
        body: "Structured training and enablement for admins, agents, supervisors, and end users — at launch, during change, and as an ongoing capability that keeps your technology investment performing long after go-live.",
        primaryCta: { label: "Plan your enablement programme", href: talk },
        secondaryCta: { label: "Download training methodology", href: talk },
        tertiaryCta: { label: "Talk to a specialist", href: talk },
    },
};
