import type { Service } from "./types";
import { close, process, service, solve, stories, talk } from "./links";

export const bespokeEngineering: Service = {
    slug: "bespoke-engineering",
    number: "06",
    icon: "code",
    title: "Bespoke Engineering",
    cardDescription: "When off-the-shelf doesn't fit, we build exactly what you need.",
    eyebrow: "06 · Engineering",
    headline: "When off-the-shelf doesn't fit, we build exactly what you need.",
    highlight: "exactly what you need",
    summary:
        "Custom agent desktops, AI voice bots, analytics solutions, workflow automation, and platform extensions — engineered to your specifications, built to production standards, and delivered by the same team who understands the platforms they run on.",
    heroImage: {
        src: "/services/bespoke-engineering.jpg",
        alt: "Engineers sketching a custom interface beside a laptop",
    },
    accentColor: "#7B5AA6",
    bgTint: "#F4EEF8",
    primaryCta: { label: "Tell us what you want to build", href: close },
    secondaryCta: { label: "Explore Nexus", href: "#nexus" },
    problem: {
        eyebrow: "What we solve",
        title: "Out-of-the-box is a starting point.",
        intro: "What you need is what actually runs your business. Generic configurations, dashboards, and workflows create generic outcomes. We build custom applications, AI tools, and integrations that take your platform from its default configuration to one genuinely engineered for how your organisation operates.",
        pains: [
            {
                title: "Platforms that don't match your workflow",
                body: "Standard agent desktops, IVR menus, and reporting screens designed for the average use case — not yours. Every workaround your team builds around a platform limitation signals that bespoke engineering would deliver better results.",
            },
            {
                title: "AI that was never trained on your data",
                body: "Out-of-the-box AI bots trained on generic intents miss the specific queries your customers actually ask. We build and train conversational AI on your real customer interactions — so it resolves, not just deflects.",
            },
            {
                title: "Reporting that shows what the platform tracks — not what matters to you",
                body: "Default dashboards surface default metrics. We build the analytics solutions that surface the specific performance data your leadership team needs to make decisions — no more exporting to spreadsheets to find the answer.",
            },
        ],
    },
    offeringsIntro: {
        eyebrow: "Capabilities",
        title: "If the platform won't do it natively, we build it.",
        body: "Production-grade. Documented. Yours to own. Every bespoke build we deliver is handed over with full source code, documentation, and support runbooks. We don't build dependencies — we build capabilities your team can maintain, understand, and build on top of.",
    },
    offerings: [
        {
            id: "agent-desktop",
            number: "01",
            title: "Agent Desktop Applications",
            lede: "A unified agent workspace built for the way your agents actually work — not the way the platform assumes they do.",
            body: "Standard agent desktops give every contact centre the same interface regardless of how different their operations are. We build custom agent desktop applications that consolidate every system your agents use — CRM, ticketing, telephony, knowledge base, and AI assist — into a single, context-aware workspace designed around your specific workflows, customer journeys, and performance requirements. The result is faster handle times, fewer errors, and agents who aren't tab-switching between five applications on every call.",
            includedLabel: "What's included",
            included: [
                "Custom agent workspace design — workflow mapping, UX design, and prototype review before development begins",
                "Unified screen pop — CRM record, interaction history, and customer context surfaced automatically on call connect",
                "Embedded telephony controls — call handling, transfer, hold, and disposition from within the custom desktop",
                "AI assist integration — next-best-action recommendations, knowledge base search, and real-time transcription embedded",
                "Automated post-call workflow — call logging, ticket creation, and follow-up task assignment triggered on disposition",
                "Role-based views — different desktop configurations for agents, supervisors, and quality analysts",
            ],
            primaryCta: { label: "Tell us what you need", href: close },
            secondaryCta: { label: "See how we build", href: process },
        },
        {
            id: "voice-bots",
            number: "02",
            title: "AI-Powered Voice Bots",
            lede: "Production-grade conversational voice bots — trained on your customers' real intents, not generic templates.",
            body: "We build AI-powered voice bots on Amazon Lex, Google CCAI, and custom NLU platforms — designed for the specific customer queries, authentication requirements, and backend integrations your contact centre handles. Unlike out-of-the-box IVR or generic bot templates, our voice bots are trained on real interaction data from your environment — which means higher containment rates, lower misrouting, and a self-service experience your customers actually complete rather than abandon. Live deployments include AI voice bots on Amazon Connect for customer authentication, order management, and appointment scheduling across multiple enterprise clients worldwide.",
            includedLabel: "What's included",
            included: [
                "Intent design and NLU model training — built from your actual customer interaction data and use case requirements",
                "Multi-turn conversation design — complex, context-aware conversation flows that handle ambiguity naturally",
                "Backend system integration — CRM, ticketing, order management, and authentication systems connected in real time",
                "Escalation design — graceful handoff to a human agent with full conversation context preserved",
                "Multi-language support — English, Hindi, Arabic, Malay, and additional languages based on your market requirements",
                "Performance monitoring — containment rate, escalation triggers, and intent confidence tracked post-deployment",
            ],
            primaryCta: { label: "Build your voice bot", href: close },
            secondaryCta: { label: "See AWS platform details", href: solve },
        },
        {
            id: "chatbots",
            number: "03",
            title: "AI Chatbots & Virtual Agents",
            lede: "Multi-channel AI chatbots that resolve — not just respond — across web, WhatsApp, and digital channels.",
            body: "We build conversational AI chatbots and virtual agents for web, WhatsApp, email, and in-app messaging — trained on your specific customer queries, connected to your live backend systems, and designed to complete transactions rather than simply acknowledge requests. From answering product queries to processing returns, scheduling appointments, and handling multi-step authentication, our chatbots are built to the resolution standard your customers expect from a human agent.",
            includedLabel: "What's included",
            included: [
                "Chatbot design and NLU model development — intent mapping, entity extraction, and conversation flow architecture",
                "WhatsApp Business API integration — end-to-end WhatsApp chatbot deployment with template message management",
                "Live data integration — CRM, inventory, order management, and booking system connectivity for real-time responses",
                "Generative AI response layer — RAG-based knowledge retrieval for accurate, context-aware answers at scale",
                "Multi-channel deployment — web widget, WhatsApp, in-app, and email from a single bot architecture",
                "Human handover with context — escalation to Zoom CC, Amazon Connect, or Zendesk with conversation history preserved",
            ],
            primaryCta: { label: "Build your chatbot", href: close },
            secondaryCta: { label: "Explore AI capabilities", href: solve },
        },
        {
            id: "analytics",
            number: "04",
            title: "Analytics & Reporting Solutions",
            lede: "The contact centre and CRM intelligence your leadership actually needs — surfaced automatically, not exported to spreadsheets.",
            body: "Default dashboards surface default metrics. We build custom analytics solutions that pull data from your contact centre, UC, and CRM platforms — transforming it into the specific performance intelligence your operations, sales, and leadership teams need to make faster, better-informed decisions. From real-time supervisor dashboards to AI-powered natural language reporting interfaces — we build reporting that works for the people using it, not just the platforms generating the data. A live production example: our AI-powered natural language reporting assistant for Zoom Contact Center, allowing supervisors to query live performance data in plain English without navigating multiple reporting screens.",
            includedLabel: "What's included",
            included: [
                "Custom dashboard development — Power BI, Tableau, QuickSight, or embedded dashboards built to your KPI framework",
                "Real-time data pipeline design — contact centre, UC, and CRM data unified in a single reporting layer",
                "AI-powered natural language reporting — conversational query interface for operational and management reporting",
                "Cross-platform analytics — Amazon Connect, Zoom, Zendesk, and HubSpot data combined in a single view",
                "Automated report delivery — scheduled reports pushed to stakeholders without manual compilation",
                "Custom metric design — KPIs specific to your business defined, calculated, and tracked from a single source",
            ],
            primaryCta: { label: "Build your analytics solution", href: close },
            secondaryCta: { label: "Explore AI capabilities", href: solve },
        },
        {
            id: "nexus",
            number: "05",
            title: "Nexus — Our AI-Powered Ticketing & CRM",
            lede: "AI-native ticketing and CRM built specifically for cloud contact centres — available standalone or embedded within a managed service.",
            body: "Nexus is Sysgrate's own AI-powered ticketing and CRM platform — designed from the ground up for modern contact center environments, where standard helpdesk tools were built for IT support, not customer-facing sales and service operations. Lightweight by design, AI-native from day one, and deeply integrated with Zoom, Amazon Connect, and the major omnichannel platforms — Nexus gives contact center teams the ticketing and CRM intelligence they need without the complexity and overhead of enterprise platforms built for a different purpose.",
            includedLabel: "What Nexus includes",
            included: [
                "AI-powered ticket management — automatic ticket creation, classification, and routing from every interaction channel",
                "Contact center native integration — Zoom CC, Amazon Connect, and Avaya connected as first-class data sources",
                "AI conversation summaries — automatic post-interaction summaries populated to ticket records without agent input",
                "Omnichannel interaction timeline — voice, chat, email, and social interactions unified in a single customer record",
                "Intelligent escalation routing — AI-driven priority and routing based on customer history, sentiment, and interaction content",
                "Built-in reporting — real-time and historical performance dashboards without a separate BI tool required",
            ],
            primaryCta: { label: "Explore Nexus", href: close },
            secondaryCta: { label: "Request a Nexus demo", href: close },
        },
        {
            id: "custom-api",
            number: "06",
            title: "Custom API & Middleware Development",
            lede: "When no native integration exists — we build one that does. Production-grade, documented, and yours to own.",
            body: "Not every platform combination has a pre-built connector. When the integration your business requires doesn't exist — or the available connector doesn't meet your performance, security, or data requirements — we build a purpose-built middleware layer. Every piece of custom middleware we develop is production-grade: full error handling, retry logic, monitoring, and documentation included as standard. The Brigade Group engagement — connecting Zoom Phone to SAP C4C with zero native connector available — is a live example of this capability in production today.",
            includedLabel: "What's included",
            included: [
                "API architecture design — data flow mapping, contract definition, and security specification",
                "Middleware development — REST, webhook, or event-driven integration built to your exact requirements",
                "Authentication and security — OAuth 2.0, API key management, and encrypted data transit as standard",
                "Error handling and retry logic — dead-letter queuing and alerting, so no interaction data is ever lost",
                "Full testing — unit, integration, and load testing at production-equivalent data volumes",
                "Documentation and handover — API contracts, data dictionaries, runbooks, and source code included",
            ],
            primaryCta: { label: "Discuss your middleware requirements", href: close },
            secondaryCta: { label: "See Brigade Group case study", href: stories },
        },
        {
            id: "workflow-automation",
            number: "07",
            title: "Workflow Automation",
            lede: "End-to-end process automation across CRM, ITSM, and contact centre — eliminating manual steps from every customer-facing and back-office workflow.",
            body: "Every manual step in a customer-facing workflow is a latency point — and a potential error. We design and build workflow automation across your contact center, CRM, and ITSM platforms that removes manual touchpoints from the processes that slow your team down. From post-call task automation and ticket routing logic to cross-system escalation triggers and scheduled campaign workflows — we build the automation layer that makes your platforms work together without human intervention at every step.",
            includedLabel: "What's included",
            included: [
                "Workflow mapping — current-state process documentation and automation opportunity identification",
                "Trigger design — event-based automation logic triggered by call disposition, ticket status, or CRM field changes",
                "Cross-platform orchestration — automation spanning contact center, CRM, ITSM, and communication platforms",
                "Scheduled workflow automation — campaign triggers, reminder sequences, and periodic reporting workflows",
                "Exception handling — automated escalation paths and manual override controls built into every workflow",
                "Performance monitoring — automation success rates, failure alerts, and throughput dashboards",
            ],
            primaryCta: { label: "Design your automation", href: close },
            secondaryCta: { label: "Explore Platform & Systems Integration", href: service("platform-systems-integration") },
        },
        {
            id: "platform-extensions",
            number: "08",
            title: "Platform Extensions & Add-ons",
            lede: "Custom extensions that take your core platforms beyond their standard capabilities — without replacing the platform itself.",
            body: "The most efficient way to add a capability your platform doesn't have natively is to extend it — not replace it. We build custom Zendesk apps, Amazon Connect accelerators, Zoom integrations, and HubSpot extensions that add the specific functionality your organisation requires, while staying within the platform architecture your team already understands and your IT team can support.",
            includedLabel: "What's included",
            included: [
                "Custom Zendesk apps — built on the Zendesk Apps Framework for features not available in the standard product",
                "Amazon Connect accelerators — pre-built contact flow modules, Lambda functions, and reporting components",
                "Zoom marketplace integrations — custom Zoom Apps built for internal deployment across your Zoom tenant",
                "HubSpot custom objects and workflows — CRM extensions for industry-specific data models and process requirements",
                "Custom Avaya applications — bespoke applications extending Avaya Experience Platform capabilities",
                "Platform-agnostic extensions — browser extensions, embedded widgets, and overlay applications for any platform",
            ],
            primaryCta: { label: "Tell us what you need", href: close },
            secondaryCta: { label: "Explore our platforms", href: solve },
        },
        {
            id: "speech-analytics",
            number: "09",
            title: "AI Speech & Text Analytics",
            lede: "Custom conversation intelligence — turning every recorded interaction into actionable insight your business can act on.",
            body: "We build custom AI speech and text analytics solutions that go beyond the standard analytics included with contact center platforms — providing organisation-specific keyword detection, custom sentiment models, compliance phrase monitoring, and trend analysis tuned to your industry, your products, and your specific quality framework. Where platform-native analytics surfaces generic insights, our custom solutions surface the specific intelligence your QA, compliance, and operations teams need to make decisions.",
            includedLabel: "What's included",
            included: [
                "Custom speech-to-text transcription — tuned for your industry terminology, accent variations, and product vocabulary",
                "Bespoke sentiment analysis — custom models trained on your interaction data for higher accuracy than generic models",
                "Compliance phrase detection — custom keyword and phrase libraries aligned to your regulatory requirements",
                "Topic and trend clustering — AI-driven identification of emerging themes across thousands of interactions",
                "Agent performance scoring — custom QA scorecard automation applied across 100% of recorded interactions",
                "Real-time alert triggers — supervisor alerts fired when specific phrases, sentiment thresholds, or compliance risks are detected live",
            ],
            primaryCta: { label: "Build your analytics solution", href: close },
            secondaryCta: { label: "Explore AI capabilities", href: solve },
        },
    ],
    process: {
        eyebrow: "How we build",
        title: "We build things that work when we're not in the room",
        intro: "The test of a good bespoke build is whether it runs reliably six months after delivery without Sysgrate on the phone. That is the standard we build to — full documentation, clean code, proper error handling, and monitoring that catches problems before they become incidents.",
        steps: [
            {
                number: "01",
                title: "Discover & Specify",
                body: "Requirements workshop — we document functional requirements, technical constraints, integration dependencies, and success criteria before any code is written. A signed-off specification is the basis for all development.",
            },
            {
                number: "02",
                title: "Design & Prototype",
                body: "Architecture design, UX wireframes where applicable, and a working prototype reviewed with your stakeholders before full development begins — so the build starts with alignment, not assumptions.",
            },
            {
                number: "03",
                title: "Build & Test",
                body: "Development against the agreed specification — unit tested throughout, integration tested before UAT, and load tested where performance is a requirement. Code reviewed by a senior engineer before client review.",
            },
            {
                number: "04",
                title: "UAT & Iterate",
                body: "User acceptance testing facilitated with your team — structured test cases, defect management, and iteration cycles until the build meets every agreed acceptance criterion.",
            },
            {
                number: "05",
                title: "Deploy & Handover",
                body: "Production deployment, go-live support, and full handover — source code, API documentation, data dictionaries, deployment runbooks, and support procedures included. Your team owns what we build.",
            },
        ],
    },
    relatedIntro:
        "Bespoke Engineering typically runs alongside Platform & Systems Integration and is often embedded within Experience as a Service retainers for clients who need custom capabilities built continuously.",
    related: [
        {
            title: "Platform & Systems Integration",
            blurb: "When integration requirements go beyond pre-built connectors — Bespoke Engineering builds the custom middleware layer.",
            href: service("platform-systems-integration"),
        },
        {
            title: "Experience as a Service",
            blurb: "XaaS retainers often include a bespoke engineering allocation — for custom AI capabilities, reporting tools, and extensions delivered continuously.",
            href: service("experience-as-a-service"),
        },
        {
            title: "AI practice",
            blurb: "Many bespoke builds are AI-powered — voice bots, analytics, natural language reporting. Our AI practice delivers the intelligence layer inside every custom build.",
            href: solve,
        },
    ],
    close: {
        title: "Have something specific in mind?",
        body: "Whether you have a detailed specification or just an idea of what your business needs — our engineering team will scope the requirement, recommend the right approach, and give you a clear delivery plan before any development begins.",
        primaryCta: { label: "Tell us what you want to build", href: talk },
        secondaryCta: { label: "Explore Nexus", href: "#nexus" },
        tertiaryCta: { label: "See client stories", href: stories },
    },
};
