import type { Service } from "./types";
import { close, offerings, process, service, solve, stories, talk } from "./links";

export const experienceAsAService: Service = {
    slug: "experience-as-a-service",
    number: "05",
    icon: "sparkles",
    title: "Experience as a Service",
    cardDescription:
        "Continuous innovation — without the overhead of building it in-house.",
    eyebrow: "05 · XaaS",
    headline: "Continuous innovation — without the overhead of building it in-house.",
    highlight: "without the overhead",
    summary:
        "A subscription-based model that keeps your CX and EX platforms evolving continuously — new capabilities, ongoing optimisation, and a dedicated Sysgrate team driving your technology roadmap forward every month.",
    heroImage: {
        src: "/services/experience-as-a-service.jpg",
        alt: "A product team planning the next month of platform improvements",
    },
    accentColor: "#E79AC0",
    bgTint: "#FAF0F5",
    primaryCta: { label: "Explore Experience as a Service", href: offerings },
    secondaryCta: { label: "Talk to a specialist", href: close },
    problem: {
        eyebrow: "What we solve",
        title: "Your platform is capable of far more than it's currently doing.",
        intro: "XaaS closes that gap — continuously.",
        pains: [
            {
                title: "Platforms falling behind while the technology moves forward",
                body: "New AI capabilities, new platform releases, and new integration opportunities go unrealised because no internal team has the bandwidth to act on them. XaaS provides that capacity as a managed subscription.",
            },
            {
                title: "No internal expertise to self-serve platform improvements",
                body: "Amazon Connect, Zoom Contact Center, and Zendesk are specialist platforms. Keeping them optimised requires certified engineers — not IT generalists. XaaS gives you that expertise on demand, every month.",
            },
            {
                title: "Unpredictable project budgets making innovation slow",
                body: "Every improvement requiring a new project approval slows the pace of change. A fixed monthly retainer replaces unpredictable project costs with a consistent, plannable investment.",
            },
        ],
    },
    offeringsIntro: {
        eyebrow: "XaaS capabilities",
        title: "A dedicated team, every month",
        body: "Continuous contact centre improvement, collaboration management, AI engineering, roadmap execution, licence optimisation, and a named customer success manager — delivered as a subscription.",
    },
    offerings: [
        {
            id: "cxaas",
            number: "01",
            title: "CX as a Service (CXaaS)",
            lede: "Continuous contact centre improvement — new capabilities, ongoing optimisation, every month.",
            body: "Your contact centre platform continuously evolved by a dedicated Sysgrate delivery team. New AI capabilities deployed as they become available. Routing logic refined as your business changes. New channels added as your customers move to them. All delivered monthly, against a roadmap your operations and CX leadership prioritise.",
            includedLabel: "What's included",
            included: [
                "New AI capability deployment — virtual agents, AI summaries, sentiment analytics, and agent assist features rolled out iteratively",
                "Routing and IVR optimisation — contact flows refined based on performance data and changing business requirements",
                "New channel enablement — WhatsApp, SMS, social, and chat channels added to your omnichannel environment",
                "CRM and integration enhancements — new fields, workflows, and automation added as your business processes evolve",
                "Performance analysis and recommendations — monthly review of CSAT, AHT, FCR, and abandonment data with improvement actions",
                "Platform release adoption — new features from Zoom, AWS, and Avaya evaluated and deployed where they add value",
            ],
            primaryCta: { label: "Explore CXaaS", href: close },
            secondaryCta: { label: "Talk to a specialist", href: close },
        },
        {
            id: "exaas",
            number: "02",
            title: "EX as a Service (EXaaS)",
            lede: "Ongoing UC and collaboration platform management — feature rollouts, user enablement, and performance tuning delivered continuously.",
            body: "Your Zoom Phone or Microsoft Teams voice environment — continuously managed, optimised, and expanded by a dedicated Sysgrate team. New features enabled as they're released. Adoption improved through structured enablement. AI capabilities like Zoom AI Companion and ZRA tuned for maximum performance.",
            includedLabel: "What's included",
            included: [
                "New platform feature enablement — Zoom AI Companion, ZRA updates, and Teams Copilot features rolled out as released",
                "User adoption improvement — targeted enablement for low-adoption teams and new starters onboarded continuously",
                "Call quality optimisation — ongoing MOS score analysis and network configuration refinement",
                "ZRA coaching model tuning — AI conversation intelligence models updated based on evolving sales scripts",
                "Integration expansion — new CRM fields, workflow automations, and reporting connections added monthly",
                "Monthly performance reporting — adoption metrics, call quality trends, and usage analytics reviewed",
            ],
            primaryCta: { label: "Explore EXaaS", href: close },
            secondaryCta: { label: "Explore Digital Workplace solutions", href: solve },
        },
        {
            id: "ai-retainer",
            number: "03",
            title: "AI Innovation Retainer",
            lede: "Dedicated AI engineering time — building, testing, and deploying new AI capabilities into your platforms every month.",
            body: "AI is not a one-time deployment. Models improve. New use cases emerge. Data quality evolves. Our AI Innovation Retainer gives enterprises a monthly allocation of certified AI engineering time — building and iterating conversational AI, analytics, automation, and generative AI capabilities across your contact centre, CRM, and communication platforms.",
            includedLabel: "What's included",
            included: [
                "Conversational AI iteration — intent model updates, new entity types, and conversation flow improvements based on real usage data",
                "Generative AI feature deployment — agent summaries, knowledge base search, and AI-assisted response drafting added as platforms release them",
                "AI analytics expansion — new dashboards, sentiment trend reports, and keyword tracking added",
                "Virtual agent performance review — resolution rates, escalation patterns, and containment rates analysed and improved monthly",
                "New AI use case development — sprint-based build of net-new AI capabilities identified in roadmap planning",
                "Responsible AI governance review — model performance, explainability, and compliance checked quarterly",
            ],
            primaryCta: { label: "Explore the AI retainer", href: close },
            secondaryCta: { label: "Explore AI capabilities", href: solve },
        },
        {
            id: "roadmap-execution",
            number: "04",
            title: "Technology Roadmap Execution",
            lede: "Your technology improvement backlog — delivered sprint by sprint, against a roadmap your team controls.",
            body: "Most enterprises have a technology roadmap that sits in a document and rarely moves as fast as leadership expects. Roadmap Execution as a Service gives you the delivery capacity to actually work through it — with a monthly sprint cycle, a prioritised backlog, and a Sysgrate team accountable for shipping improvements.",
            includedLabel: "What's included",
            included: [
                "Sprint planning — monthly session to prioritise backlog items and allocate delivery capacity",
                "Sprint delivery — backlog items built, tested, and deployed within the monthly cycle",
                "New feature releases — platform capability updates evaluated and recommended quarterly",
                "Backlog refinement — new improvement ideas captured, estimated, and prioritised continuously",
                "Sprint review — demonstration of completed items with your stakeholders at close of each sprint",
                "Roadmap reporting — progress against the 12-month roadmap reviewed quarterly",
            ],
            primaryCta: { label: "Explore roadmap execution", href: close },
            secondaryCta: { label: "Talk to a specialist", href: close },
        },
        {
            id: "licence-management",
            number: "05",
            title: "Platform Licence Management",
            lede: "Licence optimisation, renewal management, and usage analytics — so your technology spend aligns with actual usage.",
            body: "Enterprise platform licences are frequently over-provisioned. We manage your Zoom, Amazon Connect, Zendesk, and HubSpot licences as part of every XaaS engagement — reviewing usage, flagging over-provisioning, and ensuring every renewal decision is based on data, not habit.",
            includedLabel: "What's included",
            included: [
                "Monthly licence usage reporting — active vs assigned licences tracked across all platforms",
                "Over-provisioning identification — unused licences flagged with right-sizing recommendations",
                "Renewal planning — contract renewal dates tracked and options evaluated with sufficient lead time",
                "Upgrade and tier optimisation — platform tier recommendations as usage patterns evolve",
                "New licence procurement — additional licences at partner pricing as your organisation grows",
                "Annual licence review — full estate reviewed with commercial and usage recommendations",
            ],
            primaryCta: { label: "Explore licence management", href: close },
            secondaryCta: { label: "Get a managed services quote", href: service("managed-operations") },
        },
        {
            id: "customer-success",
            number: "06",
            title: "Dedicated Customer Success",
            lede: "A named Sysgrate customer success manager — your single point of contact across every workstream we run for you.",
            body: "Every XaaS engagement includes a dedicated Sysgrate CSM — responsible for roadmap planning, delivery coordination, escalation management, and business alignment. They know your environment, your priorities, and your stakeholders — so every interaction with Sysgrate starts with context.",
            includedLabel: "What's included",
            included: [
                "Named CSM assigned to your account from day one",
                "Monthly roadmap review — backlog prioritisation, sprint planning, and delivery progress reviewed together",
                "Escalation management — your CSM owns every escalation across Sysgrate's delivery and support teams",
                "Stakeholder reporting — regular updates for IT leadership, operations, and executive stakeholders",
                "Business alignment sessions — quarterly reviews ensuring the delivery roadmap stays aligned to evolving priorities",
                "Renewal and expansion guidance — proactive identification of where additional capability would add value",
            ],
            primaryCta: { label: "Explore Experience as a Service", href: close },
            secondaryCta: { label: "Talk to a specialist", href: close },
        },
    ],
    comparison: {
        eyebrow: "What is XaaS",
        title: "The smarter way to evolve customer and employee experience",
        intro: "A dedicated team, fixed monthly investment, and continuous delivery model designed to keep your technology moving forward.",
        columns: ["Category", "Traditional project model", "Experience as a Service"],
        rows: [
            {
                category: "How improvements happen",
                traditional: "New project commissioned for each change",
                featured: "Monthly delivery sprint against a live roadmap",
            },
            {
                category: "Budget model",
                traditional: "Variable — unpredictable project costs",
                featured: "Fixed monthly retainer — predictable investment",
            },
            {
                category: "Time to deliver a change",
                traditional: "Weeks or months to approve and start",
                featured: "Days — delivery capacity already allocated",
            },
            {
                category: "Platform knowledge",
                traditional: "New project team every engagement",
                featured: "Same team — continuous context, no ramp-up",
            },
            {
                category: "Innovation pace",
                traditional: "Slow — constrained by project cycles",
                featured: "Continuous — new capabilities added every sprint",
            },
            {
                category: "Accountability",
                traditional: "Ends at project delivery",
                featured: "Ongoing — performance reviewed monthly",
            },
            {
                category: "Internal headcount required",
                traditional: "High — significant IT bandwidth needed",
                featured: "Minimal — Sysgrate team absorbs the delivery",
            },
        ],
    },
    process: {
        eyebrow: "How it works",
        title: "Monthly delivery cycle",
        intro: "Simple monthly cycle. Continuous delivery. No project overhead.",
        steps: [
            {
                number: "Week 1",
                title: "Plan",
                body: "Sprint planning session — priorities agreed, delivery capacity allocated.",
            },
            {
                number: "Weeks 2–3",
                title: "Build",
                body: "The delivery team works through sprint items — building, testing, and preparing for deployment.",
            },
            {
                number: "Week 4",
                title: "Deploy & Review",
                body: "Sprint items are deployed, demonstrated, and reviewed against success criteria.",
            },
            {
                number: "Quarterly",
                title: "Align",
                body: "Roadmap progress, platform performance, and strategic direction reviewed with leadership.",
            },
        ],
    },
    relatedIntro:
        "Experience as a Service typically runs alongside Solution Design & Delivery and is often supported by Managed Operations and Bespoke Engineering for clients who need continuous platform improvement, optimisation, and innovation delivered through a predictable subscription model.",
    related: [
        {
            title: "Solution Design & Delivery",
            blurb: "Every XaaS engagement starts with a strong foundation. Our delivery team designs, deploys, and optimises the platforms that become part of your ongoing improvement roadmap.",
            href: service("solution-design-delivery"),
        },
        {
            title: "Managed Operations",
            blurb: "Managed Operations provides the day-to-day support, monitoring, and optimisation that keeps XaaS engagements delivering value long after go-live.",
            href: service("managed-operations"),
        },
        {
            title: "Bespoke Engineering",
            blurb: "When standard platform capabilities aren't enough, Bespoke Engineering delivers custom integrations, automations, AI capabilities, and enhancements as part of your continuous improvement program.",
            href: service("bespoke-engineering"),
        },
    ],
    close: {
        title: "Your platform is capable of far more than it's currently doing.",
        body: "Let's build toward it — together, continuously.",
        primaryCta: { label: "Explore Experience as a Service", href: offerings },
        secondaryCta: { label: "Talk to a specialist", href: talk },
        tertiaryCta: { label: "See client stories", href: stories },
    },
};
