import type { Service } from "./types";
import { close, process, service, solve, talk } from "./links";

export const managedOperations: Service = {
    slug: "managed-operations",
    number: "04",
    icon: "shield",
    title: "Managed Operations",
    cardDescription: "We run it. You focus on the business.",
    eyebrow: "04 · Operations",
    headline: "We run it. You focus on the business.",
    highlight: "You focus on the business.",
    summary:
        "24×7 monitoring, proactive support, SLA-backed operations, and continuous improvement — delivered by certified specialists who built the solution and stayed invested in keeping it running.",
    heroImage: {
        src: "/services/managed-operations.jpg",
        alt: "Operations specialist monitoring platform health on a display wall",
    },
    accentColor: "#26205A",
    bgTint: "#EAE8F5",
    primaryCta: { label: "Get a managed services quote", href: close },
    secondaryCta: { label: "See what we monitor", href: "#offering-monitoring" },
    problem: {
        eyebrow: "What we solve",
        title: "Your IT team should be driving innovation — not firefighting telephony incidents at midnight.",
        intro: "When the platforms running your contact centre and communications infrastructure need round-the-clock attention, the cost falls on your internal team — in overtime, in diverted focus, and in the slower response times that come from being stretched across too many technologies. We take that off your plate entirely.",
        pains: [
            {
                title: "No internal depth on specialist platforms",
                body: "Amazon Connect, Zoom Phone, and Crestron are specialist platforms. Most IT teams have working knowledge — not the deep expertise to diagnose and resolve complex incidents quickly. We provide that depth as a service.",
            },
            {
                title: "Reactive support instead of proactive monitoring",
                body: "Waiting for users to report problems means the damage is already done — calls missed, queues backed up, and CX degraded. We monitor proactively and resolve most issues before they surface to end users.",
            },
            {
                title: "Platforms that drift after go-live",
                body: "Contact centre configurations, routing logic, and UC policies need regular review to stay aligned with how your business operates. Without managed operations, platforms gradually drift — and performance quietly degrades.",
            },
        ],
    },
    offeringsIntro: {
        eyebrow: "Managed operations",
        title: "We don't hand off and walk away",
        body: "Every managed operations engagement starts with the same principle — the team running your platform should understand it as well as the team that built it. At Sysgrate, they are the same team.",
    },
    offerings: [
        {
            id: "offering-monitoring",
            number: "01",
            title: "24×7 Platform Monitoring",
            lede: "Issues identified and resolved before they reach your team or your customers.",
            body: "We monitor your contact centre, UC, and AV infrastructure around the clock — with automated alerting, real-time dashboards, and a response process that moves from detection to resolution without waiting for a user to raise a ticket. Our monitoring covers platform health, call quality, integration data flow, and capacity thresholds — giving us early warning signals to act before degradation becomes an incident.",
            includedLabel: "What's included",
            included: [
                "24×7 platform health monitoring across contact centre, UC, and AV infrastructure",
                "Real-time alerting — automated notifications on degradation, failure, and capacity threshold breaches",
                "Call quality monitoring — MOS scoring, jitter, packet loss, and latency tracked continuously",
                "Integration data flow monitoring — alerts on sync failures, API errors, and data anomalies",
                "Custom monitoring dashboards — accessible by your IT team in real time alongside Sysgrate's NOC",
                "Monthly health reports — platform performance, incident trend analysis, and recommended optimisations",
            ],
            primaryCta: { label: "Discuss monitoring requirements", href: close },
            secondaryCta: { label: "Get a managed services quote", href: close },
        },
        {
            id: "sla-support",
            number: "02",
            title: "SLA-Backed Support",
            lede: "Defined response times. Defined resolution times. No ambiguity when something goes wrong.",
            body: "Our managed support service is backed by a formal SLA with defined response and resolution timeframes for every severity level. Priority partner escalation channels with Zoom, AWS, Avaya, and Zendesk mean your critical incidents reach the right people at the vendor — faster than any standard support contract would allow.",
            includedLabel: "What's included",
            included: [
                "Multi-channel support — phone, email, and ticketing portal available 24×7 for P1 and P2",
                "Priority vendor escalation — direct access to Zoom, AWS, Avaya, and Zendesk priority support queues",
                "Named support engineers — the same specialists who know your environment handle your tickets",
                "Incident management — end-to-end ownership from detection through to root cause analysis and resolution",
                "Post-incident review — P1 and P2 incidents followed by a written RCA and improvement action plan",
            ],
            table: {
                columns: ["Priority", "Definition", "Response", "Resolution target"],
                rows: [
                    ["P1 — Critical", "Platform down. Business-critical impact.", "15 minutes", "4 hours"],
                    ["P2 — High", "Significant degradation. Majority of users affected.", "1 hour", "8 hours"],
                    ["P3 — Medium", "Partial impact. Workaround available.", "4 hours", "48 hours"],
                    ["P4 — Low", "Non-critical issue or change request.", "1 business day", "5 business days"],
                ],
            },
            primaryCta: { label: "Get a managed services quote", href: close },
            secondaryCta: { label: "See how we work", href: process },
        },
        {
            id: "cc-ops",
            number: "03",
            title: "Contact Centre Operations Management",
            lede: "Your contact centre configuration — kept current, optimised continuously, and aligned to how your business actually operates.",
            body: "A contact centre that matches your business perfectly at go-live needs regular attention to stay that way. Agent headcount changes. Routing logic needs updating. New channels need adding. AI models need tuning. We manage all of it — proactively — so your contact centre keeps performing as your operation evolves, without your IT team carrying the ongoing configuration burden.",
            includedLabel: "What's included",
            included: [
                "Routing and IVR management — queue updates, flow changes, and holiday routing maintained on your behalf",
                "AI and virtual agent tuning — intent model updates, knowledge base maintenance, and escalation threshold adjustment",
                "Agent and queue configuration — new agents, skill updates, and capacity adjustments processed as service requests",
                "CRM and integration maintenance — schema changes, field mapping updates, and connector version management",
                "Performance reporting — weekly and monthly operational dashboards aligned to your KPIs",
                "Proactive optimisation recommendations — quarterly reviews with specific, actionable improvement proposals",
            ],
            primaryCta: { label: "Discuss contact centre managed ops", href: close },
            secondaryCta: { label: "Explore CX solutions", href: solve },
        },
        {
            id: "uc-telephony",
            number: "04",
            title: "UC & Telephony Management",
            lede: "Zoom Phone and Teams voice — administered, managed, and running without your IT team carrying the day-to-day burden.",
            body: "Enterprise telephony requires ongoing administration that most IT teams underestimate until they're running it. User provisioning, number changes, dial plan updates, policy management, call quality monitoring — it is a continuous operational workload. We absorb it entirely — providing a fully managed UC administration service that keeps your telephony environment performing without consuming your internal resources.",
            includedLabel: "What's included",
            included: [
                "User provisioning and deprovisioning — new starters, leavers, and role changes processed as service requests",
                "Number management — DID additions, porting requests, and number reassignments handled end to end",
                "Dial plan and call routing maintenance — policy updates, hunt group changes, and auto-attendant modifications",
                "Call quality monitoring — QoS dashboards, MOS score tracking, and proactive remediation of quality degradation",
                "Device management — Poly, Yealink, and Cisco endpoint firmware updates and configuration management",
                "Zoom Revenue Accelerator management — AI model maintenance, dashboard updates, and coaching report configuration",
            ],
            primaryCta: { label: "Discuss UC managed operations", href: close },
            secondaryCta: { label: "Explore Digital Workplace solutions", href: solve },
        },
        {
            id: "av-monitoring",
            number: "05",
            title: "AV Remote Monitoring & Maintenance",
            lede: "Every room in your AV estate — monitored, maintained, and ready for the next meeting.",
            body: "AV systems that aren't monitored develop problems that only surface during the most important meetings. We provide centralised remote monitoring across your entire AV estate — proactively identifying device failures, firmware issues, and connectivity problems before they disrupt a boardroom presentation or a client meeting. Planned preventative maintenance visits keep every room performing to the standard it was installed to deliver.",
            includedLabel: "What's included",
            included: [
                "Centralised remote AV monitoring — device health, connectivity, and display status across all rooms",
                "Proactive fault detection — automated alerts on device failure, offline status, and performance degradation",
                "Remote diagnostics and resolution — the majority of AV issues resolved remotely without a site visit",
                "Firmware and software update management — scheduled updates applied outside business hours with rollback capability",
                "Planned preventative maintenance — scheduled on-site visits for physical inspection, cleaning, and calibration",
                "Room utilisation reporting — occupancy data and meeting room usage analytics delivered monthly",
            ],
            primaryCta: { label: "Discuss AV managed operations", href: close },
            secondaryCta: { label: "Explore Modern Workplace solutions", href: solve },
        },
        {
            id: "qbr",
            number: "06",
            title: "Quarterly Business Reviews & Continuous Improvement",
            lede: "We don't just report on what happened. We tell you what needs to change — and we make it happen.",
            body: "Every managed operations engagement includes structured quarterly business reviews — not a reporting dump, but a genuine performance conversation covering what has been delivered against SLA, what the data is telling us about platform performance, and what specific actions we recommend to improve outcomes in the next quarter.",
            includedLabel: "What's included",
            included: [
                "SLA performance review — response and resolution metrics measured against agreed targets",
                "Platform performance analysis — contact centre, UC, and AV performance trends across the quarter",
                "Incident trend analysis — recurring issues identified and root cause addressed before they repeat",
                "Technology roadmap alignment — platform upgrades, new capability releases, and configuration improvements reviewed",
                "Specific improvement recommendations — actionable proposals with effort, timeline, and expected outcome",
                "Forward planning — upcoming changes, capacity requirements, and technology events planned for next quarter",
            ],
            primaryCta: { label: "Get a managed services quote", href: close },
            secondaryCta: { label: "See how we work", href: process },
        },
    ],
    process: {
        eyebrow: "How we deliver",
        title: "Same team. Same expertise. Continuous accountability from go-live onward.",
        intro: "Whether we built your platform or are taking over a deployment someone else ran — our onboarding process gives us the same depth of platform knowledge before we assume operational responsibility. We don't guess at your environment. We document it.",
        steps: [
            {
                number: "Week 1–2",
                title: "Onboard",
                body: "Full platform documentation — architecture review, configuration audit, integration mapping, and monitoring tool deployment. SLA terms agreed and signed off. Named support engineers assigned.",
            },
            {
                number: "Week 2–3",
                title: "Baseline",
                body: "Performance baselines established — call quality benchmarks, platform health thresholds, and integration data flow norms set. Alert thresholds calibrated to distinguish genuine issues from expected variability.",
            },
            {
                number: "Week 3–4",
                title: "Handover",
                body: "Formal handover to managed operations — 24×7 monitoring active, support channels open, and escalation paths tested. Client IT team briefed on portal access, ticket submission, and escalation procedures.",
            },
            {
                number: "Ongoing",
                title: "Operate & Improve",
                body: "Continuous monitoring, proactive issue resolution, change management, and quarterly business reviews — with SLA performance reported monthly and improvement recommendations delivered every quarter.",
            },
        ],
    },
    relatedIntro:
        "Managed Operations typically follows Solution Design & Delivery and Platform & Systems Integration — and often runs alongside Experience as a Service for organisations wanting continuous innovation on top of operational stability.",
    related: [
        {
            title: "Solution Design & Delivery",
            blurb: "We build the solution — then transition straight into managing it. No handoff gap. No knowledge loss.",
            href: service("solution-design-delivery"),
        },
        {
            title: "Platform & Systems Integration",
            blurb: "We monitor and maintain the integrations we build — keeping every connection performing as your platforms evolve.",
            href: service("platform-systems-integration"),
        },
        {
            title: "Experience as a Service",
            blurb: "Stable operations covered — now add continuous innovation. XaaS keeps your technology evolving on top of the foundation we're managing.",
            href: service("experience-as-a-service"),
        },
    ],
    close: {
        title: "Ready to hand over the operational burden — to a team that actually knows your platform?",
        body: "Tell us what you're running — contact centre, UC, AV, or all three — and we'll give you a managed operations proposal built around your environment, your SLA requirements, and your budget within five business days.",
        primaryCta: { label: "Get a managed services quote", href: talk },
        secondaryCta: { label: "See what we monitor", href: "#offering-monitoring" },
        tertiaryCta: { label: "Talk to a specialist", href: talk },
    },
};
