import type { Service } from "./types";
import { close, process, service, solve, stories, talk } from "./links";

export const platformIntegration: Service = {
    slug: "platform-systems-integration",
    number: "03",
    icon: "network",
    title: "Platform & Systems Integration",
    cardDescription: "Your platforms, connected. No gaps. No workarounds.",
    eyebrow: "03 · Integration",
    headline: "Your platforms, connected. No gaps. No workarounds.",
    highlight: "No gaps.",
    summary:
        "Bespoke integrations between contact centre, collaboration, CRM, ITSM, and analytics — built to production standards and engineered to last. We connect the platforms your enterprise depends on — and make sure they stay connected.",
    heroImage: {
        src: "/services/platform-systems-integration.jpg",
        alt: "Two colleagues reviewing connected systems on shared screens",
    },
    accentColor: "#3E3A97",
    bgTint: "#EEEDF8",
    primaryCta: { label: "Discuss your integration requirements", href: close },
    secondaryCta: { label: "Download integration capability deck", href: close },
    problem: {
        eyebrow: "What we solve",
        title: "Connect every platform. Empower every interaction.",
        intro: "We eliminate data silos with enterprise-grade integrations that unify customer context, automate workflows, and keep systems in sync.",
        pains: [
            {
                title: "Agents working without customer context",
                body: "Give agents complete customer context before every interaction, reducing handle times and improving customer satisfaction.",
            },
            {
                title: "Manual data entry across disconnected systems",
                body: "Eliminate manual data entry with bi-directional integrations that keep every system synchronized and accurate.",
            },
            {
                title: "Point-to-point integrations that break and can't be maintained",
                body: "Enterprise-ready integrations with robust error handling, full documentation, and ongoing support.",
            },
        ],
    },
    offeringsIntro: {
        eyebrow: "Integration",
        title: "We connect the platforms your enterprise depends on",
        body: "Pre-built connectors where they exist. Custom middleware where they don't. Production-grade engineering in every case. Our integration practice covers every platform combination we work with — and plenty we've had to build from scratch.",
    },
    offerings: [
        {
            id: "crm-contact-center",
            number: "01",
            title: "CRM ↔ Contact Center Integration",
            lede: "Full customer context at every interaction — automatically, without agent intervention.",
            body: "We connect your contact center platform to your CRM — Salesforce, HubSpot, Zendesk, or SAP — with bi-directional data sync that gives agents a complete customer view before the call connects, and logs every interaction automatically when it ends. No manual entry. No tab switching. No data gaps between what the CRM holds and what the contact centre records.",
            includedLabel: "What's included",
            included: [
                "Real-time screen pop — customer record surfaced in agent workspace on inbound call or chat",
                "Automated call logging — call recording URL, duration, outcome, and agent notes synced to CRM on call end",
                "Bi-directional contact sync — CRM contact data updated by contact centre activity and vice versa",
                "Click-to-dial — outbound calls initiated from within the CRM interface without switching applications",
                "Ticket auto-creation — Zendesk or ServiceNow ticket created automatically on call initiation or completion",
                "Custom field mapping — contact centre data mapped to your specific CRM object and field structure",
            ],
            primaryCta: { label: "Discuss your CRM integration", href: close },
            secondaryCta: { label: "See platform details", href: solve },
        },
        {
            id: "itsm",
            number: "02",
            title: "ITSM Integration",
            lede: "Support tickets, incidents, and service requests — created, updated, and resolved across platforms without manual intervention.",
            body: "We integrate contact center and collaboration platforms with ITSM tools — ServiceNow, Jira, and Freshservice — so every customer interaction that requires an engineering or operations response triggers the right workflow automatically. Incidents are raised, routed, and tracked without agents leaving their workspace or operations teams chasing updates across disconnected systems.",
            includedLabel: "What's included",
            included: [
                "Automatic incident creation in ServiceNow or Jira triggered by contact centre call disposition",
                "CMDB lookup during live calls — agent sees asset history and open incidents for the customer in real time",
                "Bi-directional status sync — ITSM ticket status changes reflected in contact centre and agent workspace",
                "Priority and SLA inheritance — ticket priority set automatically based on contact centre customer tier",
                "Escalation workflow automation — unresolved tickets triggering escalation routes across both platforms",
                "Jira ↔ Zendesk sync — engineering and support ticket status linked with bi-directional comment sync",
            ],
            primaryCta: { label: "Discuss your ITSM integration", href: close },
            secondaryCta: { label: "See how we work", href: process },
        },
        {
            id: "custom-middleware",
            number: "03",
            title: "Custom Middleware Development",
            lede: "When no native integration exists — we build one that does.",
            body: "Not every platform combination has a pre-built connector. When the integration your business needs doesn't exist in any marketplace, we build a purpose-built middleware layer — designed for reliability, bi-directional data flow, and zero data loss. Every piece of custom middleware we develop is production-grade, fully documented, and handed over with source code, API contracts, and support runbooks. The Brigade Group engagement — connecting Zoom Phone to SAP C4C — is a live example of this capability in production.",
            includedLabel: "What's included",
            included: [
                "Integration architecture design — data flow mapping, API contract definition, and error handling specification",
                "Middleware development — REST API, webhook, or event-driven integration built to your exact requirements",
                "Authentication and security — OAuth, API key management, and encrypted data transit built as standard",
                "Error handling and retry logic — zero data loss design with dead-letter queuing and alert routing",
                "Full testing — unit, integration, and load testing against production-equivalent data volumes",
                "Documentation and handover — API contracts, data dictionaries, runbooks, and source code included",
            ],
            primaryCta: { label: "Discuss your middleware requirements", href: close },
            secondaryCta: { label: "See Brigade Group case study", href: stories },
        },
        {
            id: "zoom-crm",
            number: "04",
            title: "Zoom ↔ CRM Sync",
            lede: "Every Zoom call logged. Every CRM record updated. Zero manual entry.",
            body: "We connect Zoom Phone and Zoom Contact Center to HubSpot, Salesforce, Zendesk, and SAP — delivering automated call logging, CRM record updates, and ticket creation triggered by every interaction. Sales teams get complete pipeline visibility. Support teams get full interaction history. Operations teams get accurate reporting. All without anyone touching a keyboard after the call ends.",
            includedLabel: "What's included",
            included: [
                "Zoom Phone ↔ HubSpot — call activity logged to contact and deal records automatically on call completion",
                "Zoom Phone ↔ Salesforce — call outcome, recording, and duration synced to opportunity and contact objects",
                "Zoom Contact Center ↔ Zendesk — ticket auto-creation, queue data sync, and agent activity logging",
                "Zoom Revenue Accelerator ↔ CRM — AI conversation intelligence synced to CRM contact records",
                "Custom Zoom ↔ SAP C4C — bespoke middleware for SAP environments with no native Zoom connector",
                "Real-time sync — interaction data available in CRM within seconds of call completion",
            ],
            primaryCta: { label: "Discuss your Zoom integration", href: close },
            secondaryCta: { label: "Explore Zoom platform details", href: solve },
        },
        {
            id: "amazon-connect",
            number: "05",
            title: "Amazon Connect Integrations",
            lede: "Amazon Connect connected to every business system your contact centre needs to see.",
            body: "We build production-grade integrations between Amazon Connect and the enterprise systems your contact centre operation depends on — using Lambda, EventBridge, Kinesis, and the Amazon Connect API to connect voice, chat, and data flows to CRM, ITSM, analytics, and AI platforms. Every integration is architected for the scale, compliance, and performance requirements of enterprise APAC and Middle East deployments.",
            includedLabel: "What's included",
            included: [
                "Amazon Connect ↔ Salesforce — CTI adapter, case auto-creation, and real-time agent workspace integration",
                "Amazon Connect ↔ HubSpot — call logging, contact sync, and deal pipeline updates via custom connector",
                "Amazon Connect ↔ Zendesk — ticket creation, queue data sync, and agent activity logging",
                "Lambda function development — custom business logic triggered by contact centre events",
                "Kinesis data streaming — real-time contact centre data fed to BI tools, data warehouses, and analytics platforms",
                "Amazon Connect ↔ Microsoft Teams — expert finder and escalation routing between contact centre and UC environments",
            ],
            primaryCta: { label: "Discuss your Amazon Connect integration", href: close },
            secondaryCta: { label: "Explore AWS platform details", href: solve },
        },
        {
            id: "analytics-reporting",
            number: "06",
            title: "Analytics & Reporting Integrations",
            lede: "Your contact centre, UC, and CRM data unified in one reporting layer — without manual export or reconciliation.",
            body: "Leadership teams who can't see contact centre, telephony, and CRM data in a single view make slower, less accurate decisions. We build the data pipelines that pull performance data from Amazon Connect, Zoom, Zendesk, and HubSpot into a unified reporting layer — feeding Power BI, Tableau, QuickSight, or any BI tool your organisation uses, in real time or on a scheduled basis.",
            includedLabel: "What's included",
            included: [
                "Data pipeline design — source mapping, transformation logic, and destination schema definition",
                "Amazon Connect Kinesis streaming — real-time contact data flowing into data warehouse or BI platform",
                "Zoom analytics API integration — call, meeting, and queue data extracted and structured for reporting",
                "CRM reporting integration — HubSpot, Salesforce, and Zendesk data combined with contact centre metrics",
                "Custom dashboard development — Power BI, Tableau, or QuickSight dashboards built to your KPI framework",
                "Scheduled and real-time reporting — automated report delivery to stakeholders without manual compilation",
            ],
            primaryCta: { label: "Discuss your analytics integration", href: close },
            secondaryCta: { label: "See how we work", href: process },
        },
    ],
    process: {
        eyebrow: "How we build",
        title: "Production-grade integrations you can depend on",
        intro: "Designed with robust error handling, monitoring, and documentation to ensure reliability, maintainability, and long-term success.",
        steps: [
            {
                number: "01",
                title: "Discovery & Mapping",
                body: "We map source and destination systems — reviewing API documentation, authentication requirements, data models, and rate limits. Every field mapping is agreed and documented before development begins.",
            },
            {
                number: "02",
                title: "Architecture Design",
                body: "Integration architecture design — sync direction, trigger events, error handling strategy, retry logic, and data transformation specification. Reviewed and signed off before a line of code is written.",
            },
            {
                number: "03",
                title: "Build & Unit Test",
                body: "Development against agreed specification — with unit testing at every component, API mocking for unavailable endpoints, and code review by a senior integration engineer before moving to integration testing.",
            },
            {
                number: "04",
                title: "Integration & Load Testing",
                body: "End-to-end integration testing across all connected systems — with load testing at production data volumes to validate performance, error handling, and data integrity under real-world conditions.",
            },
            {
                number: "05",
                title: "Deploy & Monitor",
                body: "Production deployment with monitoring configured from day one — alerting on failures, latency spikes, and data anomalies. Full documentation and handover including API contracts, runbooks, and support procedures.",
            },
        ],
    },
    relatedIntro:
        "Platform & Systems Integration typically follows Solution Design & Delivery and often runs alongside Bespoke Engineering for custom-built integration requirements.",
    related: [
        {
            title: "Solution Design & Delivery",
            blurb: "We design and deploy the platforms first — then connect them to everything around them.",
            href: service("solution-design-delivery"),
        },
        {
            title: "Bespoke Engineering",
            blurb: "When integration requirements extend to custom applications, AI layers, or reporting tools — Bespoke Engineering picks up where standard integration ends.",
            href: service("bespoke-engineering"),
        },
        {
            title: "Managed Operations",
            blurb: "Once integrations are live — we can take over the monitoring, maintenance, and ongoing management of every connection we've built.",
            href: service("managed-operations"),
        },
    ],
    close: {
        title: "Tell us what needs to connect — and we'll tell you exactly how to do it.",
        body: "Whether you need a pre-built connector configured or a custom middleware layer built from scratch — our integration team will scope your requirements and give you a clear delivery plan before any development begins.",
        primaryCta: { label: "Discuss your integration requirements", href: talk },
        secondaryCta: { label: "Download integration capability deck", href: talk },
        tertiaryCta: { label: "See client stories", href: stories },
    },
};
