import type { Service } from "./types";
import { close, process, service, solve, stories, talk } from "./links";

export const solutionDesign: Service = {
    slug: "solution-design-delivery",
    number: "02",
    icon: "layers",
    title: "Solution Design & Delivery",
    cardDescription: "From blueprint to live — built right the first time.",
    headline: "From blueprint to live — built right the first time.",
    highlight: "built right the first time",
    summary:
        "We design and deliver enterprise technology solutions across CX, UCaaS, AV, and CRM — end to end, on time, and built to the standard that keeps performing long after go-live.",
    heroImage: {
        src: "/services/solution-design-delivery.jpg",
        alt: "Contact centre agents at a modern delivery floor",
    },
    accentColor: "#4A3E92",
    bgTint: "#F0EFF9",
    primaryCta: { label: "Talk to a delivery specialist", href: close },
    secondaryCta: { label: "See client stories", href: stories },
    problem: {
        eyebrow: "What we solve",
        title: "Where strategy becomes successful delivery",
        intro: "From architecture and integration to deployment and go-live, one team owns the entire journey — ensuring faster execution, lower risk, and better outcomes.",
        pains: [
            {
                title: "Delivery-ready architectures",
                body: "Architectures designed around your infrastructure, compliance, and operational realities — not a generic reference design.",
            },
            {
                title: "One team from plan to production",
                body: "A single team owns both solution design and implementation, so continuity holds from planning through to production.",
            },
            {
                title: "Go live 30–50% faster",
                body: "Proven delivery methodologies, certified templates, and pre-built accelerators shorten the path to go-live.",
            },
        ],
    },
    offeringsIntro: {
        eyebrow: "Delivery",
        title: "Certified expertise. Proven delivery.",
        body: "From cloud contact centres and UCaaS to AV and AI, our certified specialists deliver complex technology projects with speed, precision, and confidence.",
    },
    offerings: [
        {
            id: "cloud-contact-centre",
            number: "01",
            title: "Cloud Contact Centre Deployment",
            lede: "From legacy infrastructure to AI-native cloud contact centre — designed, built, and live.",
            body: "We design and deploy enterprise cloud contact centres on Amazon Connect, Zoom Contact Center, and Avaya — handling greenfield builds, platform migrations, and omnichannel expansions end-to-end. Every deployment includes IVR design, routing configuration, AI integration, CRM connectivity, and agent workspace setup — delivered as a single, cohesive engagement with one team accountable for the entire outcome.",
            includedLabel: "What's included",
            included: [
                "Contact centre architecture design — routing logic, IVR flows, queue configuration, and skill mapping",
                "Platform build and configuration — Amazon Connect, Zoom CC, or Avaya, from tenant setup to production",
                "Omnichannel channel configuration — voice, chat, email, WhatsApp, and social unified in one agent desktop",
                "AI and automation integration — virtual agents, intelligent IVR, and real-time analytics configured from day one",
                "CRM and ITSM integration — Salesforce, HubSpot, Zendesk, SAP connected with screen pops and auto-logging",
                "Agent and supervisor enablement — training, UAT support, and go-live readiness validation",
                "Zero-downtime cutover planning — phased migration from legacy platform with parallel-run validation",
            ],
            primaryCta: { label: "Talk to a contact centre delivery specialist", href: close },
            secondaryCta: { label: "Explore CX solutions", href: solve },
        },
        {
            id: "ucaas-telephony",
            number: "02",
            title: "UCaaS & Telephony Implementation",
            lede: "Enterprise cloud telephony — deployed without disruption, managed long after go-live.",
            body: "We deploy Zoom Phone and Microsoft Teams Direct Routing across multi-site, multi-country enterprise environments — handling everything from dial plan design and SBC architecture to number porting, device provisioning, and user onboarding. Every UCaaS engagement is delivered with a zero-downtime cutover from legacy PBX and a structured enablement programme that ensures your workforce is productive on the new platform from day one.",
            includedLabel: "What's included",
            included: [
                "Zoom Phone tenant provisioning — dial plans, call queues, auto-attendant, and policy configuration",
                "Microsoft Teams Direct Routing — SBC design, SIP trunk configuration, and voice routing setup",
                "Number porting and DID management — local, national, and international numbers worldwide",
                "Device provisioning — Poly, Yealink, and Cisco endpoint configuration and zero-touch deployment",
                "Legacy PBX cutover planning — parallel-run migration from Avaya, Cisco, or any on-premise system",
                "Zoom Revenue Accelerator (ZRA) deployment — AI conversation intelligence for sales and telemarketing teams",
                "CRM integration — Zoom Phone connected to HubSpot, Salesforce, or SAP C4C with automated call logging",
            ],
            primaryCta: { label: "Talk to a UC delivery specialist", href: close },
            secondaryCta: { label: "Explore Digital Workplace solutions", href: solve },
        },
        {
            id: "av-workplace",
            number: "03",
            title: "AV & Modern Workplace Design",
            lede: "Physical spaces designed, integrated, and commissioned for the way modern teams work.",
            body: "We design and install enterprise AV environments across boardrooms, hybrid meeting rooms, video walls, command centres, and digital signage — from initial space analysis and technology selection through to installation, commissioning, and user handover. Every AV engagement is delivered by certified engineers who understand both the hardware and the platforms running on top of it — Zoom Rooms, Microsoft Teams Rooms, Crestron, and beyond.",
            includedLabel: "What's included",
            included: [
                "Space analysis and AV design — room acoustics, display sizing, camera placement, and audio architecture",
                "Technology selection — vendor-agnostic hardware recommendation across Poly, Crestron, Barco, Jabra, and more",
                "Zoom Rooms and Microsoft Teams Rooms deployment — certified installation and platform configuration",
                "Video wall design and installation — LED and LCD arrays for operations floors, lobbies, and large format spaces",
                "Digital signage network deployment — cloud-managed content delivery across single sites or multi-location estates",
                "Crestron control system programming — room automation, scheduling, and building management integration",
                "Full commissioning, testing, and handover — punch-list sign-off and user familiarisation included",
            ],
            primaryCta: { label: "Talk to an AV delivery specialist", href: close },
            secondaryCta: { label: "Explore Modern Workplace solutions", href: solve },
        },
        {
            id: "crm-helpdesk",
            number: "04",
            title: "CRM & Helpdesk Implementation",
            lede: "Configured for your workflows. Integrated from day one. Not the platform default.",
            body: "We implement Zendesk, HubSpot, and Salesforce — configured specifically for your support and sales workflows, integrated with your contact center and communication platforms, and set up with the automation, routing, and AI capabilities that make them genuinely more effective than the out-of-the-box configuration. Every CRM implementation we deliver is built to reduce manual data entry, improve agent context, and give leadership the reporting they need to make decisions.",
            includedLabel: "What's included",
            included: [
                "Workflow design and configuration — ticket routing, SLA policies, escalation rules, and automation logic",
                "Zendesk AI agent and Copilot setup — AI-powered resolution and agent assist configured from day one",
                "HubSpot pipeline and deal stage configuration — aligned to your actual sales process, not the default template",
                "Full telephony integration — Zoom Phone, Amazon Connect, or Avaya connected with screen pops and call logging",
                "Knowledge base and help centre setup — structured content, self-service configuration, and generative search",
                "Custom reporting and dashboards — SLA tracking, agent performance, and pipeline visibility built to your business requirements",
                "Data migration — existing ticket, contact, and deal data migrated cleanly from legacy CRM or helpdesk",
            ],
            primaryCta: { label: "Talk to a CRM delivery specialist", href: close },
            secondaryCta: { label: "Explore CX solutions", href: solve },
        },
        {
            id: "legacy-migration",
            number: "05",
            title: "Legacy Platform Migration",
            lede: "Off legacy. On cloud. Without the war stories.",
            body: "We have the migration tooling, playbooks, and delivery experience to move enterprises off legacy PBX systems — onto modern cloud platforms — without downtime, without lost call history, and without the months-long timelines that most migrations carry. Our pre-built migration accelerators cut the time and risk out of every legacy cutover we manage.",
            includedLabel: "What's included",
            included: [
                "Current-state legacy assessment — infrastructure mapping, call flow documentation, and dependency analysis",
                "Migration strategy and phasing — zero-downtime cutover design with parallel-run validation at each stage",
                "IVR migration tooling — proprietary accelerators for contact flow recreation on Amazon Connect and Zoom CC",
                "Number inventory management — DID porting, carrier coordination, and routing continuity through the cutover",
                "Agent transition planning — hardware replacement, softphone deployment, and day-one training",
                "Data migration — call recordings, agent history, and configuration data transferred where platform APIs allow",
                "Hypercare support — dedicated Sysgrate engineers on-site or on-call for the first 2 weeks post-cutover",
            ],
            primaryCta: { label: "Book a migration assessment", href: close },
            secondaryCta: { label: "Download migration guide", href: close },
        },
        {
            id: "solution-architecture",
            number: "06",
            title: "Solution Architecture & Design",
            lede: "The technical foundation every successful delivery is built.",
            body: "Before any platform is configured, any integration is built, or any agent is trained — the architecture has to be right. We design target-state architectures for CX, UC, AV, and CRM environments that are technically rigorous, commercially justified, and designed to evolve as your business grows. Every architecture document we produce is a living specification — reviewed and signed off before a single line of configuration is written.",
            includedLabel: "What's included",
            included: [
                "Target architecture definition — platform selection, component design, and integration architecture",
                "Infrastructure and network assessment — connectivity, latency, security, and compliance requirements",
                "Integration design — API contracts, data flows, middleware requirements, and error handling specification",
                "Security architecture — IAM, encryption, data residency, and compliance controls mapped to each market",
                "Scalability design — architecture validated for peak load, geographic expansion, and future capability addition",
                "Technical specification documentation — detailed enough to build from, clear enough for non-technical stakeholder review",
            ],
            primaryCta: { label: "Talk to a solution architect", href: close },
            secondaryCta: { label: "See how we deliver", href: process },
        },
    ],
    process: {
        eyebrow: "How we deliver",
        title: "Fast delivery. No shortcuts. Built right the first time.",
        intro: "Speed and quality are not in conflict when you have the right methodology, the right accelerators, and the right team. Every engagement we run is structured to go live 30–50% faster than standard vendor delivery — without compromising on architecture rigour or production quality.",
        steps: [
            {
                number: "01",
                title: "Discover & Define",
                body: "We map your current environment, define functional and technical requirements, and agree on success metrics before any architecture decisions are made. Nothing is assumed. Everything is documented.",
            },
            {
                number: "02",
                title: "Design & Architect",
                body: "Target architecture, integration design, security model, and phasing plan — developed by certified solution architects and reviewed with your technical and operational stakeholders before build begins.",
            },
            {
                number: "03",
                title: "Build & Integrate",
                body: "Platform configuration, integration development, and custom build — delivered using our pre-built accelerators and certified implementation methodology. Progress tracked against agreed milestones with weekly client reporting.",
            },
            {
                number: "04",
                title: "Test & Validate",
                body: "Functional testing, integration testing, UAT facilitation, and performance validation — against the success criteria defined in step one. Nothing goes to production until it passes.",
            },
            {
                number: "05",
                title: "Go-Live & Hypercare",
                body: "Cutover execution, go-live support, and hypercare coverage for the first two weeks post-production — with dedicated Sysgrate engineers available to resolve any issue at any hour during the critical stabilisation period.",
            },
        ],
    },
    relatedIntro:
        "Solution Design & Delivery sits at the centre of most Sysgrate engagements — typically preceded by Strategy & Advisory and followed by Platform & Systems Integration or Managed Operations.",
    related: [
        {
            title: "Strategy & Advisory",
            blurb: "Not sure what to build? Start with an advisory engagement — platform selection, roadmap, or business case — before committing to delivery.",
            href: service("strategy-advisory"),
        },
        {
            title: "Platform & Systems Integration",
            blurb: "Need the platforms we deliver connected to your existing enterprise stack? Integration is the next service in the sequence.",
            href: service("platform-systems-integration"),
        },
        {
            title: "Managed Operations",
            blurb: "Once your solution is live — we can take over the ongoing management, monitoring, and continuous improvement.",
            href: service("managed-operations"),
        },
    ],
    close: {
        title: "Ready to build something that performs from day one?",
        body: "Whether you're deploying a cloud contact centre, migrating off a legacy PBX, or rolling out AV across a new headquarters, our delivery team is ready to design it, build it, and hand it over live.",
        primaryCta: { label: "Talk to a delivery specialist", href: talk },
        secondaryCta: { label: "See client stories", href: stories },
        tertiaryCta: { label: "Download our delivery methodology", href: talk },
    },
};
