import type { Service } from "./types";
import { close, process, service, solve, stories, talk } from "./links";

export const strategyAdvisory: Service = {
    slug: "strategy-advisory",
    number: "01",
    icon: "compass",
    title: "Strategy & Advisory",
    cardDescription:
        "Clarity before commitment. We help you make the right technology decisions.",
    eyebrow: "01 · Advisory",
    headline: "Clarity before commitment.",
    highlight: "commitment",
    summary:
        "We help enterprises make the right technology decisions before they spend a dollar in the wrong direction — independent advisory, no vendor agenda, built around your outcomes.",
    heroImage: {
        src: "/services/strategy-advisory.jpg",
        alt: "Leadership team reviewing a technology roadmap in a meeting room",
    },
    accentColor: "#9A6EAC",
    bgTint: "#F5F0FA",
    primaryCta: { label: "Book a free discovery call", href: close },
    secondaryCta: { label: "Download AI readiness guide", href: close },
    problem: {
        eyebrow: "What we solve",
        title: "Stop technology failures before they start",
        intro: "The most common reasons enterprise technology projects fail have nothing to do with the technology itself. We resolve all — at the front end, before they become expensive problems.",
        pains: [
            {
                title: "Vendor-led decisions with no independent view",
                body: "When the platform decision is made by the vendor selling it, the outcome is always the same — the wrong fit, too much license, and a project that tries to solve problems the platform wasn't designed for.",
            },
            {
                title: "Projects starting without a clear outcome definition",
                body: "Technology transformations without defined success metrics become moving targets. Scope creep, budget overruns, and post-launch disappointment are almost always the result of skipping the outcomes conversation at the start.",
            },
            {
                title: "No business case — no internal buy-in",
                body: "Technology leaders who can't quantify the return on their investment don't get the budget. We build the commercial and operational case that gets the right projects approved, funded, and started.",
            },
        ],
    },
    offeringsIntro: {
        eyebrow: "Advisory",
        title: "Build the strategy before you choose the technology",
        body: "From CX and UC roadmaps to AI readiness and vendor selection, we help organizations make informed technology decisions with confidence.",
    },
    offerings: [
        {
            id: "cx-uc-roadmaps",
            number: "01",
            title: "CX & UC Technology Roadmaps",
            lede: "A clear path from where you are to where your business needs to be.",
            body: "We build structured 12–36 month technology roadmaps for enterprise CX, UCaaS, and modern workplace environments — aligned to your business objectives, your budget cycle, and the platform capabilities available to you today and in the near term. A Sysgrate roadmap is not a wish list. It is a sequenced, prioritised plan with defined milestones, dependencies, and ownership — the kind that actually gets executed.",
            includedLabel: "What's included",
            included: [
                "Current-state technology and process assessment across CX, UC, and the workplace",
                "Target architecture definition — where you need to be in 12, 24, and 36 months",
                "Prioritised initiative sequencing with dependencies mapped and risks identified",
                "Platform and vendor recommendations aligned to your target state",
                "Budget phasing and investment planning across the roadmap horizon",
                "Executive-ready roadmap presentation for board and leadership sign-off",
            ],
            primaryCta: { label: "Book a roadmap session", href: close },
            secondaryCta: { label: "See how we work", href: process },
        },
        {
            id: "ai-readiness",
            number: "02",
            title: "AI Readiness Assessment",
            lede: "Understand where AI will actually move the needle — before you invest in it.",
            body: "Most enterprises approaching AI for the first time have the same challenge — everyone is talking about it, but nobody can agree on where to start, what to automate, or how to measure success. Our AI Readiness Assessment gives you a structured, independent view of your current maturity, your highest-value AI use cases, and a realistic deployment path — without vendor bias, without hype, and with a business case your CFO can review.",
            includedLabel: "What's included",
            included: [
                "AI maturity scoring across data, process, technology, and organisational readiness",
                "Use case identification and prioritisation — by ROI potential and implementation complexity",
                "Platform and tooling assessment — AWS Bedrock, Zoom AI, Azure OpenAI, and more",
                "Data readiness review — quality, availability, and governance assessment",
                "Risk and compliance assessment — regulatory requirements across the world",
                "AI deployment roadmap with quick wins, medium-term initiatives, and long-term vision",
                "Business case with ROI projections for the top three prioritised use cases",
            ],
            primaryCta: { label: "Book an AI readiness assessment", href: close },
            secondaryCta: { label: "Download the AI readiness guide", href: close },
        },
        {
            id: "vendor-selection",
            number: "03",
            title: "Vendor & Platform Selection",
            lede: "The right platform for your business — recommended without a vendor agenda.",
            body: "We are certified across Zoom, AWS, Avaya, Microsoft, Zendesk, HubSpot, and more — which means we can make a genuinely informed recommendation across all of them, based on your specific requirements rather than which one we're most incentivised to sell. Our platform selection process is structured, evidence-based, and independent — designed to give you the confidence that the platform you choose is the right one for your organisation.",
            includedLabel: "What's included",
            included: [
                "Requirements gathering — functional, technical, compliance, and commercial",
                "Platform long-listing and screening against defined criteria",
                "Weighted scoring matrix across all shortlisted platforms and vendors",
                "Proof-of-concept design and facilitation for final shortlist evaluation",
                "Commercial negotiation support and licence optimisation guidance",
                "Final recommendation report with rationale, risks, and implementation considerations",
            ],
            primaryCta: { label: "Talk to an independent advisor", href: close },
            secondaryCta: { label: "Explore our platforms", href: solve },
        },
        {
            id: "business-case",
            number: "04",
            title: "Business Case Development",
            lede: "The commercial argument that gets your technology project approved and funded.",
            body: "Technology leaders who can't quantify the return on their investment don't get the budget. We build rigorous, evidence-based business cases that quantify the cost of inaction, model the financial return, and present the operational and commercial benefits in language that resonates with CFOs, boards, and procurement teams — so the right technology projects get the green light they deserve.",
            includedLabel: "What's included",
            included: [
                "Cost of current-state analysis — quantifying the operational and commercial cost of the status quo",
                "TCO modelling — total cost of ownership across 3 and 5-year investment horizons",
                "ROI and payback period calculation with sensitivity analysis",
                "Operational benefit quantification — productivity, AHT, CSAT, and cost-per-contact improvements",
                "Risk analysis — implementation risk, change management risk, and mitigation strategies",
                "Executive presentation deck and supporting financial model",
            ],
            primaryCta: { label: "Start your business case", href: close },
            secondaryCta: { label: "See how we work", href: process },
        },
        {
            id: "current-state-audit",
            number: "05",
            title: "Current-State Audit & Gap Analysis",
            lede: "Understand exactly where you are before you decide where to go.",
            body: "You can't plan a transformation without knowing what you're transforming. Our current-state audit gives enterprises a clear, honest view of their existing CX, UC, or workplace technology environment — what's working, what isn't, where the gaps are, and what those gaps are actually costing the business. We benchmark your environment against industry best practice and your peers, giving you the context to make confident decisions about what to change and in what order.",
            includedLabel: "What's included",
            included: [
                "Technology infrastructure review — platforms, integrations, and architecture assessment",
                "Process and workflow audit — identifying friction points and inefficiency across CX and UC",
                "Performance benchmarking — AHT, CSAT, first-contact resolution, and SLA adherence",
                "Compliance and risk assessment — data handling, call recording, and regulatory exposure",
                "Gap analysis report — current state vs best practice with prioritised improvement recommendations",
                "Quick-win identification — changes that can be made immediately without significant investment",
            ],
            primaryCta: { label: "Book a current-state audit", href: close },
            secondaryCta: { label: "Download our audit methodology", href: close },
        },
        {
            id: "transformation-strategy",
            number: "06",
            title: "Digital Transformation Strategy",
            lede: "A transformation strategy that your entire organisation can execute — not just read.",
            body: "Digital transformation is not a technology programme. It is an organisational change programme that happens to involve technology. The strategies that succeed treat people, process, and platform with equal priority — and plan for the change management required to make the technology land. We build transformation strategies that are commercially grounded, operationally realistic, and designed to get the full organisation moving in the same direction.",
            includedLabel: "What's included",
            included: [
                "Transformation vision definition — where the organisation needs to be and why",
                "Stakeholder mapping and change impact assessment",
                "People, process, and technology workstream planning",
                "Programme structure and governance design — roles, accountability, and decision rights",
                "Change management and communications strategy",
                "Benefits realisation framework — how transformation success will be measured and tracked",
                "Executive and board-ready strategy document with supporting business case",
            ],
            primaryCta: { label: "Talk to a transformation specialist", href: close },
            secondaryCta: { label: "See client stories", href: stories },
        },
    ],
    process: {
        eyebrow: "How we work",
        title: "Every advisory engagement ends with a decision you can act on",
        intro: "Our methodology is deliberately structured so every advisory output is actionable, commercially justified, and ready for internal approval — not a report that sits on a shelf.",
        steps: [
            {
                number: "01",
                title: "Discover",
                body: "We embed ourselves in your environment — interviewing stakeholders, reviewing existing technology, assessing current processes, and understanding the commercial and operational context before forming any view.",
            },
            {
                number: "02",
                title: "Analyse",
                body: "We benchmark your current state against best practice, identify gaps and opportunities, and develop a clear point of view on the highest-value path forward — independent of any vendor relationship.",
            },
            {
                number: "03",
                title: "Define",
                body: "We translate analysis into a structured output — roadmap, business case, platform recommendation, or transformation strategy — with clear rationale, commercial justification, and a plan your organisation can execute.",
            },
            {
                number: "04",
                title: "Align",
                body: "We present findings to your leadership team, facilitate the alignment conversation, and refine the output to reflect internal priorities and constraints — ensuring every recommendation has genuine organisational buy-in before delivery begins.",
            },
        ],
    },
    relatedIntro:
        "Strategy & Advisory typically leads directly into one or more of these — depending on what the engagement recommends.",
    related: [
        {
            title: "Solution Design & Delivery",
            blurb: "Once the strategy is defined and the platform selected — we build and deploy it.",
            href: service("solution-design-delivery"),
        },
        {
            title: "Customer Experience",
            blurb: "CX roadmaps and AI assessments typically lead to contact centre transformation engagements.",
            href: solve,
        },
        {
            title: "Digital Workplace",
            blurb: "UC technology roadmaps and vendor selection lead to UCaaS and collaboration deployments.",
            href: solve,
        },
    ],
    close: {
        title: "Not sure where to start? That's exactly what we're here for.",
        body: "Every advisory engagement begins with a free discovery call — no commitment, no sales pitch. Just a straight conversation about your technology challenges and what the right next step looks like for your business.",
        primaryCta: { label: "Book a free discovery call", href: talk },
        secondaryCta: { label: "Talk to a specialist", href: talk },
        tertiaryCta: { label: "Download AI readiness guide", href: talk },
    },
};
